### ISSUE TITLE
Jars?

### ISSUE THREAD

**Issue by Mune03** [joulupunikki/Phoenix#1]
"Copy `Phoenix.jar`,`Phoenix.bat` and `Phoenix1280x1024.bat` and `PHOENIX` directory to your EFS directory where `EFS.EXE`"

I cannot find any Phoenix.jar, Phoenix.bat, and build.bat files in any of the directories.  All I see in the /etc/ is PHOENIX.INI file.

I am running Windows 7 and have all java jdk/jre installed.

**Comment by joulupunikki** [comment]
It seems this was a documentation/packaging bug. Parts of the README were up to two years old and partly reflected the much more simple way of doing releases when initial Phoenix jars were published on various file sharing sites. As a result it was possible to get a bare set of sources with documentation speaking about non-existent jars and build files. The documentation is now upgraded to reflect the current three ways of getting Phoenix: binary distribution, source distribution and snapshot/clone of the raw database.  A new [release](https://github.com/joulupunikki/Phoenix/releases) was also published with the updated documentation.  As of this writing, [Phoenix_0.10.2.zip](https://github.com/joulupunikki/Phoenix/releases/download/v0.10.2/Phoenix_0.10.2.zip) is the latest binary/jar distribution and [Phoenix_src_0.10.2.zip](https://github.com/joulupunikki/Phoenix/releases/download/v0.10.2/Phoenix_src_0.10.2.zip) is the (hopefully) easily compilable source distribution.
