### ISSUE TITLE
Separate graphics from

### ISSUE THREAD

**Issue by kevin-d-kelly** [joulupunikki/Phoenix#79]
Hi just found this on a trip down memory lane and impressed with whats been done so far. I understand and agree with your principle of recreating the original efs to begin with but dont know java and am eager to help. The graphics are showing their age and this would be an area i could help with, however the formats are prehistoric and suffer major limitations. How difficult would it be to check for and load higher resolution 32bit grahics say in png form rather than the bin and pcx files? I knocked together a quick and dirty uprezed version of the first file in pcx folder here: 
https://imgur.com/AccWBJ0

**Comment by joulupunikki** [comment]
Here we also have to consider the composition, not just the individual graphics. Right now EFS is visually dated, but it's also a balanced whole where everything fits together (other than the low res and 8-bits.) Even the fonts are well thought out in the original EFS, whereas the fonts in Phoenix will require more tuning to blend in as well as the originals. In the course of creating Phoenix I've noticed that even tiny deviations from the original look may hurt the aesthetics. So, increasing resolutions and colour depth would not be enough, all the individual graphics would have to be redone and then the whole would have to be balanced.

Also, from the point of view of this project, unless and until the basic game works, time spent on coding support for better graphics will delay the game at best and will be time wasted on vapour ware at worst. Among other things, for single player an AI far better than the original will have to be implemented, and even for just the multiplayer certain factions need some AI to make for a useful game.

A real graphics format upgrade would also probably require tinkering with hardware graphics support, currently the graphics processing is done with the cpu and it eats a lot of cpu time and cache.

A feature of the original graphics which needs to be done is finishing the flc-player for unit window animations, issue #7

So, closing this for now.

**Comment by kevin-d-kelly** [comment]
Understood, but an obvious first step would be to convert the original graphic to png without changing their appearance. Again i'm not familiar with java, PHP and javascript are my forte and i dont really know whats happening on the rendering side but it seems to me that having the graphics abstracted from the original formats early on allows a certain degree of future proofing as well as getting a bit more interest from players and mod makers and doesnt involve changing appearance, just format. 

But you're right in saying the ai and gameplay are much more important, and you know better than me the complexity of the work involved. Bin files would be the main issue i think. If you're not going to do it though i'll make a fork and give it a shot, do you have a copy of Maciej Swierzewski's editor to convert the bin files by any chance?

Re issue 7, most people use the cut down version thats available or mods with a different unit set that dont include these files so i wouldnt make it a high priority, but again your project your decision.
